resolversList: ./re.txt
proxy : ""
subfinder:
  - subfinderConfigFile: /mnt/e/Github/BugBountyCatch/subfinder.yaml
  - Thread: 10
  - Silent: true
  - All: true
  - RemoveWildcard: true
shuffledns:
  - subdomainWordList: ./sub.txt
  - Threads: 10000
  - StrictWildcard: false
  - WildcardThreads: 25
  - Silent : true
naabu:
  - Threads: 20
  - TopPorts: 1000
  - Silent: true
  - OutputCDN: false
httpx:
  - Methods: GET
  - StatusCode: true
  - Location: true
  - TechDetect: true
  - ExtractTitle: true
  - OutputIP: true
  - OutputCName: true
  - Threads: 100
  - FollowHostRedirects: true
  - Silent: true
