subfinderConfigFile: /mnt/e/Github/BugBountyCatch/subfinder.yaml
Thread: 10
resolversList: /mnt/e/Github/BugBountyCatch/re.txt
subdomainWordList: /mnt/e/Github/BugBountyCatch/sub.txt
massdnsPath: bin/massdns